displayName=OSRS Settlement
author=Bart Jolink
description=Build up a settlement in the sidebar, fuelled by your skilling, slaying, bossing and clue hunting
tags=settlement,town,build,building,bounty,xp,skilling,boss,clue
plugins=com.osrssettlement.SettlementPlugin
build=standard